name: Issue Translator

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Language
        id: language-check
        uses: usthe/check-issue-language-action@v1.0

      - name: Translate Issue
        id: translation
        uses: usthe/translate-issue-action@v1.0
        with:
          issue_language: ${{ steps.language-check.outputs.language }}
          is_modify_title: false
          custom_bot_note: Bot detected the issue body's language is not English, translate it automatically.